# Generated by Django 5.2.1 on 2026-06-12 02:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0005_rumahdinas_unit_kerja'),
        ('tanah_negara', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermohonanPenghapusanBMN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nomor_permohonan', models.CharField(blank=True, max_length=120, unique=True)),
                ('tanggal_permohonan', models.DateField(default=django.utils.timezone.now)),
                ('jenis_aset', models.CharField(choices=[('KENDARAAN', 'Kendaraan'), ('RUMAH_NEGARA', 'Rumah Negara'), ('TANAH_NEGARA', 'Tanah Negara'), ('LAINNYA', 'BMN Lainnya')], max_length=30)),
                ('kode_barang', models.CharField(blank=True, max_length=100, null=True)),
                ('nup', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_barang', models.CharField(max_length=220)),
                ('nilai_perolehan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('kondisi_barang', models.CharField(blank=True, max_length=120, null=True)),
                ('lokasi_barang', models.TextField(blank=True, null=True)),
                ('alasan_penghapusan', models.CharField(choices=[('RUSAK_BERAT', 'Rusak Berat'), ('HILANG', 'Hilang'), ('MUSNAH', 'Musnah'), ('TIDAK_EKONOMIS', 'Tidak Ekonomis untuk Diperbaiki'), ('IDLE_TIDAK_DIGUNAKAN', 'Idle/Tidak Digunakan'), ('PENYERAHAN_PENGELOLA', 'Penyerahan kepada Pengelola Barang'), ('ALIH_STATUS', 'Alih Status Penggunaan'), ('PEMINDAHTANGANAN', 'Pemindahtanganan'), ('LAINNYA', 'Lainnya')], max_length=40)),
                ('uraian_alasan', models.TextField(verbose_name='Uraian Alasan/Kronologi')),
                ('dasar_usulan', models.TextField(blank=True, help_text='Contoh: hasil pemeriksaan fisik, rusak berat, idle, hilang, atau dasar administratif lain.', null=True, verbose_name='Dasar Usulan')),
                ('dokumen_usulan', models.FileField(blank=True, help_text='Surat usulan/nota dinas dari unit kerja.', null=True, upload_to='penghapusan/usulan/')),
                ('dokumen_pendukung', models.FileField(blank=True, help_text='BA pemeriksaan, foto kondisi, dokumen kepemilikan, atau lampiran lain.', null=True, upload_to='penghapusan/pendukung/')),
                ('foto_kondisi', models.ImageField(blank=True, null=True, upload_to='penghapusan/foto/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DIAJUKAN', 'Diajukan Unit Kerja'), ('DIVERIFIKASI_BIRO', 'Diverifikasi Biro Umum'), ('PERLU_PERBAIKAN', 'Perlu Perbaikan Usulan'), ('DITOLAK', 'Ditolak'), ('DISETUJUI', 'Disetujui'), ('PROSES_PENGHAPUSAN', 'Proses Penghapusan'), ('SELESAI', 'Selesai/Dihapuskan')], default='DIAJUKAN', max_length=30)),
                ('catatan_unit', models.TextField(blank=True, null=True)),
                ('catatan_biro_umum', models.TextField(blank=True, null=True)),
                ('tanggal_verifikasi', models.DateField(blank=True, null=True)),
                ('nomor_persetujuan', models.CharField(blank=True, max_length=150, null=True)),
                ('tanggal_persetujuan', models.DateField(blank=True, null=True)),
                ('dokumen_persetujuan', models.FileField(blank=True, null=True, upload_to='penghapusan/persetujuan/')),
                ('nomor_sk_penghapusan', models.CharField(blank=True, max_length=150, null=True)),
                ('tanggal_sk_penghapusan', models.DateField(blank=True, null=True)),
                ('dokumen_sk_penghapusan', models.FileField(blank=True, null=True, upload_to='penghapusan/sk/')),
                ('berita_acara_penghapusan', models.FileField(blank=True, null=True, upload_to='penghapusan/ba/')),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permohonan_penghapusan_dibuat', to=settings.AUTH_USER_MODEL)),
                ('diperbarui_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permohonan_penghapusan_diperbarui', to=settings.AUTH_USER_MODEL)),
                ('diverifikasi_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifikasi_penghapusan', to=settings.AUTH_USER_MODEL)),
                ('kendaraan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permohonan_penghapusan', to='master.kendaraan')),
                ('pemohon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permohonan_penghapusan', to='master.pegawai')),
                ('rumah_negara', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permohonan_penghapusan', to='master.rumahdinas')),
                ('tanah_negara', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permohonan_penghapusan', to='tanah_negara.tanahnegara')),
                ('unit_kerja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permohonan_penghapusan', to='master.unitkerja')),
            ],
            options={
                'verbose_name': 'Permohonan Penghapusan BMN',
                'verbose_name_plural': 'Permohonan Penghapusan BMN',
                'ordering': ['-tanggal_permohonan', '-created_at'],
            },
        ),
    ]
