# Generated by ChatGPT for SIKARIS
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('penghapusan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoKondisiPenghapusanBMN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('foto', models.ImageField(upload_to='penghapusan/foto_multi/')),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
                ('diupload_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('permohonan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_kondisi_list', to='penghapusan.permohonanpenghapusanbmn')),
            ],
            options={
                'verbose_name': 'Foto Kondisi Penghapusan BMN',
                'verbose_name_plural': 'Foto Kondisi Penghapusan BMN',
                'ordering': ['-created_at'],
            },
        ),
    ]
