# Generated by ChatGPT patch
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('penghapusan', '0003_penghapusan_tte_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangPenghapusanBMN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nomor_urut', models.PositiveIntegerField(default=1)),
                ('kode_barang', models.CharField(blank=True, max_length=100, null=True)),
                ('nup', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_barang', models.CharField(max_length=220)),
                ('jenis_aset', models.CharField(choices=[('KENDARAAN', 'Kendaraan'), ('RUMAH_NEGARA', 'Rumah Negara'), ('TANAH_NEGARA', 'Tanah Negara'), ('LAINNYA', 'BMN Lainnya')], default='LAINNYA', max_length=30)),
                ('kuantitas', models.PositiveIntegerField(default=1)),
                ('nilai_perolehan', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('kondisi_barang', models.CharField(blank=True, max_length=120, null=True)),
                ('lokasi_barang', models.TextField(blank=True, null=True)),
                ('alasan_penghapusan', models.CharField(choices=[('RUSAK_BERAT', 'Rusak Berat'), ('HILANG', 'Hilang'), ('MUSNAH', 'Musnah'), ('TIDAK_EKONOMIS', 'Tidak Ekonomis untuk Diperbaiki'), ('IDLE_TIDAK_DIGUNAKAN', 'Idle/Tidak Digunakan'), ('PENYERAHAN_PENGELOLA', 'Penyerahan kepada Pengelola Barang'), ('ALIH_STATUS', 'Alih Status Penggunaan'), ('PEMINDAHTANGANAN', 'Pemindahtanganan'), ('LAINNYA', 'Lainnya')], default='RUSAK_BERAT', max_length=40)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('permohonan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_barang', to='penghapusan.permohonanpenghapusanbmn')),
            ],
            options={
                'verbose_name': 'Detail Barang Penghapusan BMN',
                'verbose_name_plural': 'Detail Barang Penghapusan BMN',
                'ordering': ['nomor_urut', 'id'],
            },
        ),
    ]
