# Generated by Django 4.2.30 on 2026-06-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penghapusan', '0004_barang_penghapusan_bmn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permohonanpenghapusanbmn',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft/Konsep'), ('DIAJUKAN_UNIT_KERJA', 'Diajukan Unit Kerja'), ('MENUNGGU_VERIFIKASI_BIRO_UMUM', 'Menunggu Verifikasi Biro Umum'), ('DIVERIFIKASI_BIRO_UMUM', 'Diverifikasi Biro Umum'), ('PERLU_PERBAIKAN', 'Perlu Perbaikan Usulan'), ('DIAJUKAN_KE_DIRJEN_REHSOS', 'Diajukan ke Dirjen Rehsos'), ('DISETUJUI_DIRJEN_REHSOS', 'Disetujui Dirjen Rehsos'), ('DITOLAK_DIRJEN_REHSOS', 'Ditolak Dirjen Rehsos'), ('DIAJUKAN_KE_SEKJEN', 'Diajukan ke Sekjen'), ('DITOLAK_SEKJEN', 'Ditolak Sekjen'), ('SK_PENGHAPUSAN_TERBIT', 'SK Penghapusan Terbit'), ('SELESAI', 'Selesai/Dihapuskan'), ('DIAJUKAN', 'Diajukan Unit Kerja'), ('DIVERIFIKASI_BIRO', 'Diverifikasi Biro Umum'), ('DIAJUKAN_SEKJEN', 'Diajukan ke Sekjen'), ('SK_TERBIT', 'SK Penghapusan Terbit'), ('DITOLAK', 'Ditolak'), ('DISETUJUI', 'Disetujui'), ('PROSES_PENGHAPUSAN', 'Proses Penghapusan')], default='MENUNGGU_VERIFIKASI_BIRO_UMUM', max_length=30),
        ),
    ]
