# Generated by Django 4.2.30 on 2026-06-19 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barang_lainnya', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sipbaranglainnya',
            options={'ordering': ['-tanggal_sip', '-created_at'], 'verbose_name': 'SIP Barang Lainnya', 'verbose_name_plural': 'SIP Barang Lainnya'},
        ),
        migrations.AlterModelOptions(
            name='sipbaranglainnyaitem',
            options={'ordering': ['urutan', 'id'], 'verbose_name': 'Item SIP Barang Lainnya', 'verbose_name_plural': 'Item SIP Barang Lainnya'},
        ),
    ]
