# Generated by Django 5.2.1 on 2026-06-12 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_jenis_kendaraan_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumahdinas',
            name='unit_kerja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rumah_negara', to='master.unitkerja'),
        ),
    ]
