# Generated by ChatGPT for SIKARIS
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_kendaraan_dokumen_stnk_bpkb'),
    ]

    operations = [
        migrations.AddField(
            model_name='kendaraan',
            name='keterangan_status_pemanfaatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rumahdinas',
            name='keterangan_status_pemanfaatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kendaraan',
            name='status_pemanfaatan',
            field=models.CharField(choices=[('TERSEDIA', 'Tersedia'), ('DIGUNAKAN', 'Digunakan'), ('DALAM_SERVICE', 'Dalam Service'), ('TIDAK_AKTIF', 'Tidak Aktif'), ('TIDAK_DIKETAHUI', 'Tidak Diketahui Keberadaannya'), ('DIKUASAI_PIHAK_LAIN', 'Dikuasai Pihak Lain')], default='TERSEDIA', max_length=30),
        ),
        migrations.AlterField(
            model_name='rumahdinas',
            name='status_pemanfaatan',
            field=models.CharField(choices=[('KOSONG', 'Kosong'), ('DIHUNI', 'Dihuni'), ('DALAM_PERBAIKAN', 'Dalam Perbaikan'), ('TIDAK_AKTIF', 'Tidak Aktif'), ('DALAM_PENGUASAAN_PIHAK_LAIN', 'Dalam Penguasaan Pihak Lain')], default='KOSONG', max_length=30),
        ),
    ]
