# Generated by ChatGPT on 2026-06-18
from django.db import migrations, models
import core.constants


def map_status_penggunaan(apps, schema_editor):
    Kendaraan = apps.get_model('master', 'Kendaraan')
    mapping = {
        'TERSEDIA': 'BMN_TIDAK_DIGUNAKAN',
        'DIGUNAKAN': 'DIGUNAKAN_SENDIRI_OPERASIONAL',
        'DALAM_SERVICE': 'DIGUNAKAN_SENDIRI_OPERASIONAL',
        'TIDAK_AKTIF': 'BMN_TIDAK_DIGUNAKAN',
        'TIDAK_DIKETAHUI': 'BMN_TIDAK_DIGUNAKAN',
        'DIKUASAI_PIHAK_LAIN': 'DIGUNAKAN_PIHAK_LAIN',
        'DIOPERASIONALKAN_SATKER_LAIN': 'DIGUNAKAN_SATKER_LAIN_DALAM_KL',
        'Dioperasionalkan Satker Lain': 'DIGUNAKAN_SATKER_LAIN_DALAM_KL',
        'Digunakan sendiri untuk operasional': 'DIGUNAKAN_SENDIRI_OPERASIONAL',
    }
    for obj in Kendaraan.objects.all().only('pk', 'status_penggunaan'):
        value = obj.status_penggunaan
        new_value = mapping.get(value, value)
        if not new_value:
            new_value = 'DIGUNAKAN_SENDIRI_OPERASIONAL'
        if new_value != value:
            obj.status_penggunaan = new_value
            obj.save(update_fields=['status_penggunaan'])


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_alter_kendaraan_jenis_kendaraan_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kendaraan',
            old_name='status_pemanfaatan',
            new_name='status_penggunaan',
        ),
        migrations.AlterField(
            model_name='kendaraan',
            name='status_penggunaan',
            field=models.CharField(
                choices=core.constants.STATUS_PENGGUNAAN_KENDARAAN,
                default='DIGUNAKAN_SENDIRI_OPERASIONAL',
                max_length=100,
            ),
        ),
        migrations.RunPython(map_status_penggunaan, migrations.RunPython.noop),
    ]
