# Generated by ChatGPT on 2026-06-18
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_rename_kendaraan_status_penggunaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='kendaraan',
            name='pejabat_penandatangan_sip',
            field=models.ForeignKey(
                blank=True,
                help_text='Pejabat penandatangan/penerbit SIP Kendaraan. Data ini menjadi sumber tanda tangan pada PDF SIP.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='kendaraan_pejabat_penandatangan_sip',
                to='master.pegawai',
            ),
        ),
    ]
