# Generated by Django 4.2.30 on 2026-06-10 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kendaraan', '0002_alter_sip_jenis_kendaraan_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuktiKuitansiServiceKendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='service_kendaraan/kuitansi/')),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
                ('diupload_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bukti_kuitansi', to='kendaraan.servicekendaraan')),
            ],
            options={
                'verbose_name': 'Bukti Kuitansi Service Kendaraan',
                'verbose_name_plural': 'Bukti Kuitansi Service Kendaraan',
                'ordering': ['-created_at'],
            },
        ),
    ]
