# Generated by Django 4.2.30 on 2026-06-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kendaraan', '0006_normalisasi_status_sip_kendaraan'),
        ('kendaraan', '0007_sip_penerbit_unit_tte'),
    ]

    operations = [
    ]
