# Generated by Django 4.2.30 on 2026-06-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kendaraan', '0008_merge_20260615_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipkendaraan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft/Konsep'), ('DIAJUKAN', 'Diajukan'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak'), ('TERBIT', 'Terbit'), ('MENUNGGU_TTE', 'Menunggu TTE BSrE'), ('BERAKHIR', 'Berakhir'), ('DIBATALKAN', 'Dibatalkan')], default='DRAFT', max_length=25),
        ),
    ]
