# Generated by ChatGPT for SIKARIS workflow update
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kendaraan', '0009_alter_sipkendaraan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sipkendaraan',
            name='file_tte_pengusul',
            field=models.FileField(blank=True, null=True, upload_to='sip_kendaraan/tte_pengusul/'),
        ),
        migrations.AddField(
            model_name='sipkendaraan',
            name='status_tte_pengusul',
            field=models.CharField(choices=[('BELUM', 'Belum TTE Pengusul'), ('SUDAH_TTE', 'Sudah TTE Pengusul')], default='BELUM', max_length=20),
        ),
        migrations.AddField(
            model_name='sipkendaraan',
            name='tanggal_tte_pengusul',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sipkendaraan',
            name='catatan_tte_pengusul',
            field=models.TextField(blank=True, null=True),
        ),
    ]
