# Generated by ChatGPT for optional SIP supporting documents
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kendaraan', '0010_tte_pengusul_sip_kendaraan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sipkendaraan',
            name='dokumen_lainnya',
            field=models.FileField(blank=True, help_text='Opsional. Upload lampiran pendukung seperti surat tugas, nota dinas, identitas, atau dokumen lain yang diperlukan.', null=True, upload_to='sip_kendaraan/lampiran_lainnya/', verbose_name='Dokumen Lainnya / Lampiran Pendukung (Opsional)'),
        ),
    ]
