# Generated by Django 4.2.30 on 2026-06-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kendaraan', '0011_sipkendaraan_dokumen_lainnya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipkendaraan',
            name='nomor_sip',
            field=models.CharField(blank=True, help_text='Otomatis dari sistem jika dikosongkan. Format: nomor/1/PL.02/SIKARIS/bulan/tahun, contoh 2/1/PL.02/SIKARIS/01/2025', max_length=100, unique=True),
        ),
    ]
