# Generated by Django 5.2.1 on 2026-06-12 03:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0005_rumahdinas_unit_kerja'),
        ('tanah_negara', '0003_tanahnegara_kab_kota_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermohonanPSPBMN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nomor_permohonan', models.CharField(blank=True, max_length=120, unique=True)),
                ('tanggal_permohonan', models.DateField(default=django.utils.timezone.now)),
                ('jenis_barang', models.CharField(choices=[('KENDARAAN', 'Kendaraan'), ('RUMAH_NEGARA', 'Rumah Negara'), ('TANAH_NEGARA', 'Tanah Negara'), ('LAINNYA', 'BMN Lainnya')], max_length=30)),
                ('kode_barang', models.CharField(blank=True, max_length=100, null=True)),
                ('nup', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_barang', models.CharField(max_length=220)),
                ('nilai_psp', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('kondisi_barang', models.CharField(blank=True, max_length=120, null=True)),
                ('lokasi_barang', models.TextField(blank=True, null=True)),
                ('keterangan_barang', models.TextField(blank=True, null=True)),
                ('surat_permohonan_satker', models.FileField(blank=True, null=True, upload_to='psp/surat_permohonan_satker/')),
                ('surat_pengantar_eselon1', models.FileField(blank=True, null=True, upload_to='psp/surat_pengantar_eselon1/')),
                ('daftar_kondisi_barang', models.FileField(blank=True, null=True, upload_to='psp/daftar_kondisi_barang/')),
                ('laporan_sub_kelompok_barang', models.FileField(blank=True, null=True, upload_to='psp/laporan_sub_kelompok_barang/')),
                ('surat_pernyataan_kepala_satker', models.FileField(blank=True, null=True, upload_to='psp/surat_pernyataan_kepala_satker/')),
                ('foto_kendaraan', models.FileField(blank=True, null=True, upload_to='psp/foto_kendaraan/')),
                ('dokumen_kepemilikan', models.FileField(blank=True, null=True, upload_to='psp/dokumen_kepemilikan/')),
                ('surat_pernyataan_pengganti_kepemilikan', models.FileField(blank=True, null=True, upload_to='psp/surat_pernyataan_pengganti_kepemilikan/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DIAJUKAN', 'Diajukan Unit Kerja'), ('DIVERIFIKASI_BIRO', 'Diverifikasi Biro Umum'), ('PERLU_PERBAIKAN', 'Perlu Perbaikan Usulan'), ('DITOLAK', 'Ditolak'), ('DISETUJUI', 'Disetujui/Penetapan PSP'), ('SELESAI', 'Selesai')], default='DIAJUKAN', max_length=30)),
                ('catatan_unit', models.TextField(blank=True, null=True)),
                ('catatan_biro_umum', models.TextField(blank=True, null=True)),
                ('tanggal_verifikasi', models.DateField(blank=True, null=True)),
                ('nomor_penetapan_psp', models.CharField(blank=True, max_length=150, null=True)),
                ('tanggal_penetapan_psp', models.DateField(blank=True, null=True)),
                ('dokumen_penetapan_psp', models.FileField(blank=True, null=True, upload_to='psp/penetapan_psp/')),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permohonan_psp_dibuat', to=settings.AUTH_USER_MODEL)),
                ('diperbarui_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permohonan_psp_diperbarui', to=settings.AUTH_USER_MODEL)),
                ('diverifikasi_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifikasi_psp', to=settings.AUTH_USER_MODEL)),
                ('kendaraan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permohonan_psp', to='master.kendaraan')),
                ('pemohon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permohonan_psp', to='master.pegawai')),
                ('rumah_negara', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permohonan_psp', to='master.rumahdinas')),
                ('tanah_negara', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permohonan_psp', to='tanah_negara.tanahnegara')),
                ('unit_kerja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permohonan_psp', to='master.unitkerja')),
            ],
            options={
                'verbose_name': 'Permohonan PSP BMN',
                'verbose_name_plural': 'Permohonan PSP BMN',
                'ordering': ['-tanggal_permohonan', '-created_at'],
            },
        ),
    ]
