# Generated by ChatGPT for SIKARIS
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permohonanpspbmn',
            name='dokumen_permohonan_psp',
            field=models.FileField(blank=True, help_text='Gabungan surat permohonan, pengantar, daftar kondisi, laporan sub kelompok, dan surat pernyataan dalam satu PDF.', null=True, upload_to='psp/dokumen_permohonan/'),
        ),
        migrations.RenameField(
            model_name='permohonanpspbmn',
            old_name='nomor_penetapan_psp',
            new_name='nomor_sk_psp',
        ),
        migrations.RenameField(
            model_name='permohonanpspbmn',
            old_name='tanggal_penetapan_psp',
            new_name='tanggal_sk_psp',
        ),
        migrations.RenameField(
            model_name='permohonanpspbmn',
            old_name='dokumen_penetapan_psp',
            new_name='sk_penetapan_psp',
        ),
        migrations.AlterField(
            model_name='permohonanpspbmn',
            name='nama_barang',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='permohonanpspbmn',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DIAJUKAN', 'Diajukan Unit Kerja'), ('DIVERIFIKASI_BIRO', 'Diverifikasi Biro Umum'), ('PERLU_PERBAIKAN', 'Perlu Perbaikan Usulan'), ('DITOLAK', 'Ditolak'), ('DISETUJUI', 'Disetujui'), ('PROSES_PSP', 'Proses Penetapan PSP'), ('SELESAI', 'Selesai')], default='DIAJUKAN', max_length=30),
        ),
        migrations.CreateModel(
            name='FotoBarangPSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('foto', models.ImageField(upload_to='psp/foto_barang/')),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
                ('diupload_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('permohonan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_barang_list', to='psp.permohonanpspbmn')),
            ],
            options={
                'verbose_name': 'Foto Barang PSP',
                'verbose_name_plural': 'Foto Barang PSP',
                'ordering': ['-created_at'],
            },
        ),
    ]
