# Generated by Django 4.2.30 on 2026-06-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp', '0003_psp_banyak_barang_nomor_tte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permohonanpspbmn',
            name='nomor_nota_permohonan_psp',
            field=models.CharField(blank=True, help_text='Nomor dapat diedit manual pada dokumen Word hasil generate.', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='permohonanpspbmn',
            name='status_tte',
            field=models.CharField(choices=[('BELUM', 'Menunggu Penetapan'), ('SIAP_TTE', 'Siap TTE BSrE'), ('PROSES_TTE', 'Proses TTE BSrE'), ('SUDAH_TTE', 'Sudah TTE BSrE'), ('DITOLAK_TTE', 'Ditolak TTE BSrE')], default='BELUM', max_length=20),
        ),
    ]
