# Generated by Django 5.2.1 on 2026-06-12 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_jenis_kendaraan_choices'),
        ('rumah_dinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siprumahdinas',
            name='bukti_bayar_pnbp',
            field=models.FileField(blank=True, null=True, upload_to='pnbp_rumah_negara/'),
        ),
        migrations.AddField(
            model_name='siprumahdinas',
            name='nilai_pnbp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='siprumahdinas',
            name='penghuni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sip_rumah_dihuni', to='master.pegawai', verbose_name='Penghuni Aktual'),
        ),
        migrations.AddField(
            model_name='siprumahdinas',
            name='status_bayar_pnbp',
            field=models.CharField(choices=[('SUDAH_BAYAR', 'Sudah Bayar'), ('BELUM_BAYAR', 'Belum Bayar'), ('TIDAK_WAJIB', 'Tidak Wajib')], default='BELUM_BAYAR', max_length=20),
        ),
        migrations.AddField(
            model_name='siprumahdinas',
            name='tahun_pnbp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siprumahdinas',
            name='tanggal_bayar_pnbp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siprumahdinas',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sip_rumah', to='master.pegawai', verbose_name='Pemegang SIP'),
        ),
    ]
