# Generated by Django 4.2.30 on 2026-06-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_dinas', '0004_nomor_sip_otomatis_tte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siprumahdinas',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DIAJUKAN', 'Diajukan'), ('DIAJUKAN_SEKJEN', 'Diajukan ke Sekretaris Jenderal'), ('DISETUJUI_SEKJEN', 'Disetujui Sekretaris Jenderal'), ('DITOLAK_SEKJEN', 'Ditolak Sekretaris Jenderal'), ('DIAJUKAN_KABIRO', 'Diajukan ke Kepala Biro Umum'), ('DISETUJUI_KABIRO', 'Disetujui Kepala Biro Umum'), ('DITOLAK_KABIRO', 'Ditolak Kepala Biro Umum'), ('DISETUJUI', 'Disetujui'), ('MENUNGGU_TTE', 'Menunggu TTE BSrE'), ('AKTIF', 'Aktif'), ('BERAKHIR', 'Berakhir'), ('DICABUT', 'Dicabut'), ('DITOLAK', 'Ditolak'), ('DIBATALKAN', 'Dibatalkan'), ('PENGOSONGAN', 'Dalam Proses Pengosongan')], default='DRAFT', max_length=25),
        ),
    ]
