# Generated by Django 4.2.30 on 2026-06-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_dinas', '0006_sip_rumah_tte_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siprumahdinas',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft/Konsep'), ('DIAJUKAN', 'Diajukan'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak'), ('TERBIT', 'Terbit'), ('MENUNGGU_TTE', 'Menunggu TTE BSrE'), ('BERAKHIR', 'Berakhir'), ('DIBATALKAN', 'Dibatalkan'), ('PENGOSONGAN', 'Dalam Proses Pengosongan')], default='DRAFT', max_length=25),
        ),
    ]
