# Generated by ChatGPT for optional SIP supporting documents
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_dinas', '0008_sip_rumah_tte_calon_pengguna'),
    ]

    operations = [
        migrations.AddField(
            model_name='siprumahdinas',
            name='dokumen_lainnya',
            field=models.FileField(blank=True, help_text='Opsional. Upload lampiran pendukung seperti surat pernyataan, identitas, dokumen keluarga, atau dokumen lain yang diperlukan.', null=True, upload_to='sip_rumah_dinas/lampiran_lainnya/', verbose_name='Dokumen Lainnya / Lampiran Pendukung (Opsional)'),
        ),
    ]
