# Generated by Django 4.2.30 on 2026-06-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_dinas', '0009_siprumahdinas_dokumen_lainnya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siprumahdinas',
            name='nomor_sip',
            field=models.CharField(blank=True, help_text='Otomatis dari sistem jika dikosongkan. Format: nomor/1.5/PL.03/SIKARIS/bulan/tahun, contoh 1/1.5/PL.03/SIKARIS/01/2026', max_length=100, unique=True),
        ),
    ]
