# Generated by ChatGPT for SIKARIS SIP Rumah Negara update

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_kendaraan_pejabat_penandatangan_sip'),
        ('rumah_dinas', '0010_alter_siprumahdinas_nomor_sip'),
    ]

    operations = [
        migrations.AddField(
            model_name='siprumahdinas',
            name='pejabat_penandatangan_pegawai',
            field=models.ForeignKey(blank=True, help_text='Dipilih oleh Pengelola BMN dari Master Pegawai. Data ini akan ditampilkan pada PDF SIP Rumah Negara.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sip_rumah_ditandatangani', to='master.pegawai', verbose_name='Nama Pejabat Penandatangan'),
        ),
        migrations.AddField(
            model_name='siprumahdinas',
            name='nama_pejabat_penandatangan',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='siprumahdinas',
            name='nip_pejabat_penandatangan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siprumahdinas',
            name='jabatan_pejabat_penandatangan',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
