# Generated by Django 5.2.1 on 2026-06-12 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0004_alter_jenis_kendaraan_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TanahNegara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kode_tanah', models.CharField(max_length=80, unique=True)),
                ('nama_tanah', models.CharField(max_length=180)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('provinsi', models.CharField(blank=True, max_length=100, null=True)),
                ('kabupaten_kota', models.CharField(blank=True, max_length=100, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=100, null=True)),
                ('kelurahan', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('luas_tanah', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('nup', models.CharField(blank=True, max_length=100, null=True)),
                ('kode_barang', models.CharField(blank=True, max_length=100, null=True)),
                ('nilai_perolehan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('nomor_sertifikat', models.CharField(blank=True, max_length=150, null=True)),
                ('tanggal_sertifikat', models.DateField(blank=True, null=True)),
                ('status_tanah', models.CharField(choices=[('DIGUNAKAN', 'Digunakan'), ('IDLE', 'Idle'), ('SENGKETA', 'Sengketa dengan Warga'), ('DISEWAKAN', 'Disewakan/Dimanfaatkan'), ('LAINNYA', 'Lainnya')], default='DIGUNAKAN', max_length=30)),
                ('digunakan_oleh', models.CharField(blank=True, max_length=200, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('dokumen_sertifikat', models.FileField(blank=True, null=True, upload_to='tanah_negara/sertifikat/')),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit_kerja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanah_negara', to='master.unitkerja')),
            ],
            options={
                'verbose_name': 'Tanah Negara',
                'verbose_name_plural': 'Tanah Negara',
                'ordering': ['kode_tanah'],
            },
        ),
    ]
