# Generated by Django 5.2.1 on 2026-06-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanah_negara', '0002_excel_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanahnegara',
            name='kab_kota',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tanahnegara',
            name='digunakan_oleh',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='tanahnegara',
            name='kabupaten_kota',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tanahnegara',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='tanahnegara',
            name='kelurahan',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='tanahnegara',
            name='provinsi',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
